{
  "hash": "8bae081cf2a5ccd61b1f417efef71960",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"10. Constrained Least Squares\"\nsubtitle: \"Equality and inequality restrictions, and partial identification\"\n---\n\nThe previous chapter tested restrictions by comparing an unrestricted Wald statistic with a robust covariance matrix to its critical value. Some restricted-vs.-unrestricted machinery (the distance test, the LR-style criterion comparison) needs the *restricted* estimator: minimize SSE subject to the restriction. That is **constrained least squares** (CLS).\n\nCLS is also useful in its own right:\n\n- **Theory imposes structure.** Adding-up constraints (shares sum to 1), monotonicity (returns to schooling weakly increasing), sign restrictions (a price elasticity is non-positive) can all be encoded as restrictions on $\\bm{\\beta}$.\n- **Partial identification.** When the data and minimal assumptions tell us only that $\\bm{\\beta}$ lies in a *set*, not a single point, inequality CLS lets us estimate that set and report the bounds.\n\nThis chapter covers:\n\n1. Equality CLS — two ways to compute (reparameterize, or apply the closed-form formula)\n2. The connection back to the Wald test (restricted SSE feeds the homoskedastic special case; the robust Wald is the right thing to report)\n3. Inequality CLS — when the restriction is one-sided, via quadratic programming\n4. A partial-identification application: bounds on the NSW employment ATE under missing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sandwich)\nlibrary(lmtest)\nlibrary(estimatr)\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'car' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'carData' was built under R version 4.5.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(carData)\nlibrary(quadprog)   # QP for inequality CLS\nlibrary(lpSolve)    # LP for the bounds at the end\noptions(digits = 4)\ndata(Salaries)\n```\n:::\n\n\n\n## The setup\n\nCLS minimizes the sum of squared errors subject to $q$ linear restrictions:\n$$\n\\tilde{\\bm{\\beta}}_{\\text{CLS}} \\;=\\; \\arg\\min_{\\bm{\\beta}} \\; \\sum_{i=1}^{n}(Y_i - \\bm{X}_i'\\bm{\\beta})^2\n\\quad \\text{s.t.} \\quad \\bm{R}'\\bm{\\beta} \\;=\\; \\bm{r}\n$$\nwhere $\\bm{R}$ is $k \\times q$ and $\\bm{r}$ is $q \\times 1$. Three common forms:\n\n| Restriction | $\\bm{R}'$ | $\\bm{r}$ |\n|---|---|---|\n| $\\beta_3 = 0$ (exclusion) | $(0, 0, 1, 0)$ | $0$ |\n| $\\beta_2 = \\beta_3$ (equality of two coefficients) | $(0, 1, -1, 0)$ | $0$ |\n| $\\beta_2 + \\beta_3 = 1$ (adding-up) | $(0, 1, 1, 0)$ | $1$ |\n\nThe exclusion restriction is the trivial case --- \"drop the regressor.\" The other two need either reparameterization or the closed-form formula below.\n\n\n## Equality CLS by reparameterization\n\nUse the `Salaries` data from `carData`. The model:\n$$\n\\text{salary}_i = \\alpha + \\gamma_{\\text{rank}} + \\delta_{\\text{discipline}} + \\beta_2\\,\\text{yrs.since.phd}_i + \\beta_3\\,\\text{yrs.service}_i + e_i.\n$$\nA natural restriction to test is $H_0: \\beta_2 = \\beta_3$ --- does an additional year since the PhD pay the same as an additional year of service at this institution? Becker--Mincer human-capital theory would predict the two should *differ* (firm-specific tenure should pay more), so the equality is something we test against, not something we believe a priori.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_U <- lm(salary ~ rank + discipline + yrs.since.phd + yrs.service,\n            data = Salaries)\n\n## Reparameterize: under H0, regress on the SUM of the two\nmod_R <- lm(salary ~ rank + discipline + I(yrs.since.phd + yrs.service),\n            data = Salaries)\n\ncbind(unrestricted = c(coef(mod_U), NA),\n      restricted   = c(coef(mod_R)[1:4], NA, NA, coef(mod_R)[5]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              unrestricted restricted\n(Intercept)        69869.0  72017.929\nrankAssocProf      12831.5  13886.660\nrankProf           45287.7  48116.640\ndisciplineB        14505.2  13720.558\nyrs.since.phd        534.6         NA\nyrs.service         -476.7         NA\n                        NA     -6.376\n```\n\n\n:::\n:::\n\n\nIn the restricted regression, the coefficient on `I(yrs.since.phd + yrs.service)` is the common $\\tilde{\\beta}_2 = \\tilde{\\beta}_3$. This is just OLS on a rebuilt design matrix --- no special machinery needed.\n\nNote that the unrestricted estimates have *opposite signs* (+535 for `yrs.since.phd`, −477 for `yrs.service`): once `rank` is in the model, `yrs.service` measures extra years at the same rank without promotion, which signals lower productivity or weaker outside options and depresses salary. The two variables are nearly collinear ($\\rho = 0.91$), so forcing them equal averages a strong positive against a strong negative --- the constrained common coefficient will land near zero, exactly the signal that the restriction is at odds with the data.\n\n\n## Equality CLS via the closed-form formula\n\nThe general formula. Solving the constrained minimization with Lagrange multipliers gives\n$$\n\\tilde{\\bm{\\beta}}_{\\text{CLS}} \\;=\\; \\hat{\\bm{\\beta}}_{\\text{OLS}} - (\\bm{X}'\\bm{X})^{-1}\\bm{R}\\bigl[\\bm{R}'(\\bm{X}'\\bm{X})^{-1}\\bm{R}\\bigr]^{-1}\\bigl(\\bm{R}'\\hat{\\bm{\\beta}}_{\\text{OLS}} - \\bm{r}\\bigr).\n$$\nRead it as: start from unrestricted OLS, subtract a correction proportional to *how far OLS violates the restriction*. If OLS already satisfies the restriction ($\\bm{R}'\\hat{\\bm{\\beta}}_{\\text{OLS}} = \\bm{r}$), the correction is zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeta_OLS <- coef(mod_U)\nX <- model.matrix(mod_U)\ny <- Salaries$salary\n\n## Build R for the restriction beta_phd = beta_service\nR <- matrix(0, nrow = length(beta_OLS), ncol = 1)\nR[which(names(beta_OLS) == \"yrs.since.phd\"), 1] <-  1\nR[which(names(beta_OLS) == \"yrs.service\"),   1] <- -1\nr <- 0\n\nXX_inv <- solve(crossprod(X))\ncorrection <- XX_inv %*% R %*%\n  solve(t(R) %*% XX_inv %*% R) %*% (t(R) %*% beta_OLS - r)\nbeta_CLS <- as.vector(beta_OLS - correction)\nnames(beta_CLS) <- names(beta_OLS)\nbeta_CLS\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) rankAssocProf      rankProf   disciplineB yrs.since.phd \n    72017.929     13886.660     48116.640     13720.558        -6.376 \n  yrs.service \n       -6.376 \n```\n\n\n:::\n:::\n\n\nThe two `yrs.since.phd` and `yrs.service` entries should now be equal --- and equal to the coefficient on `I(yrs.since.phd + yrs.service)` from the reparameterized fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncommon_value <- coef(mod_R)[[\"I(yrs.since.phd + yrs.service)\"]]\nc(formula_phd     = unname(beta_CLS[\"yrs.since.phd\"]),\n  formula_service = unname(beta_CLS[\"yrs.service\"]),\n  reparam_common  = common_value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    formula_phd formula_service  reparam_common \n         -6.376          -6.376          -6.376 \n```\n\n\n:::\n:::\n\n\nAll three match. Two routes, same answer.\n\n\n## Restricted SSE and the test\n\nThe headline test of $H_0: \\beta_2 = \\beta_3$ is the **robust Wald** built directly from the unrestricted estimator and a heteroskedasticity-robust covariance matrix. The restricted CLS estimator is not needed for this test --- but it is what makes the *classical F* well-defined as a homoskedastic special case.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Headline: robust Wald (use this).\nlinearHypothesis(mod_U, \"yrs.since.phd = yrs.service\",\n                 vcov. = vcovHC(mod_U, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nyrs.since.phd - yrs.service = 0\n\nModel 1: restricted model\nModel 2: salary ~ rank + discipline + yrs.since.phd + yrs.service\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df    F Pr(>F)  \n1    392                 \n2    391  1 2.84  0.093 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nBehind the scenes the classical F equals\n$$\nF \\;=\\; \\frac{(\\text{SSE}_R - \\text{SSE}_U)/q}{\\text{SSE}_U/(n - k)},\n$$\na comparison of the *restricted* CLS sum of squares to the unrestricted OLS sum of squares. We can compute this from CLS directly and confirm `linearHypothesis()` returns the same thing under its homoskedastic default:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSSE_U <- sum(residuals(mod_U)^2)\nSSE_R <- sum(residuals(mod_R)^2)\nn     <- nrow(Salaries)\nk     <- length(coef(mod_U))\nq     <- 1\n\nF_stat <- ((SSE_R - SSE_U) / q) / (SSE_U / (n - k))\np_val  <- 1 - pf(F_stat, q, n - k)\nc(F = F_stat, p = p_val)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      F       p \n5.37937 0.02089 \n```\n\n\n:::\n:::\n\n\nUnder heteroskedasticity the classical $F$ has the wrong null distribution (it ignores the variation in $\\text{Var}(e_i \\mid X_i)$); the robust Wald above is what you should report. CLS earns its keep here mainly when you actually need the *restricted estimator itself* --- for inequality constraints (next sections), for the GMM distance test you saw in the IV chapter, or for imposing a theoretical structure as the headline regression.\n\n\n## Inequality CLS\n\nEquality CLS pins $\\bm{\\beta}$ to a $(k-q)$-dimensional subspace. **Inequality CLS** restricts $\\bm{\\beta}$ to a feasible region $\\mathcal{B}$ defined by linear inequalities $\\bm{R}'\\bm{\\beta} \\le \\bm{r}$ --- a polyhedron rather than a subspace. Examples:\n\n- **Sign restrictions**: $\\beta_j \\ge 0$ (a variance, a non-negative elasticity, a share)\n- **Box constraints**: $0 \\le \\beta_j \\le 1$ (mixing weights, probabilities)\n- **Monotonicity**: $\\beta_1 \\le \\beta_2 \\le \\beta_3$ (ordered effects, e.g., dose-response that should be weakly increasing)\n\nThe strategy is two-step. Compute unrestricted OLS first. If $\\hat{\\bm{\\beta}}_{\\text{OLS}} \\in \\mathcal{B}$, no constraint binds and $\\tilde{\\bm{\\beta}}_{\\text{CLS}} = \\hat{\\bm{\\beta}}_{\\text{OLS}}$. Otherwise the constrained solution sits on the boundary of $\\mathcal{B}$, where one or more constraints hold with equality. Conceptually you are *projecting* OLS onto the feasible region.\n\nThe general algorithm is a quadratic program: minimize $\\frac{1}{2}\\bm{\\beta}'(\\bm{X}'\\bm{X})\\bm{\\beta} - (\\bm{X}'\\bm{y})'\\bm{\\beta}$ subject to the inequalities. In R, use `quadprog::solve.QP()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Suppose we want to estimate the salary regression but\n## restrict the discipline coefficient to be NON-NEGATIVE\n## (theoretical-economics premium, say).\nmod_qp <- lm(salary ~ rank + discipline + yrs.since.phd + yrs.service,\n             data = Salaries)\nbeta_OLS <- coef(mod_qp)\ndisc_idx <- which(names(beta_OLS) == \"disciplineB\")\ncat(\"OLS coefficient on disciplineB:\", round(beta_OLS[disc_idx], 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS coefficient on disciplineB: 14505 \n```\n\n\n:::\n\n```{.r .cell-code}\n## QP setup\nX <- model.matrix(mod_qp)\ny <- Salaries$salary\nDmat <- crossprod(X)\ndvec <- crossprod(X, y)\n\n## Constraint: beta_disciplineB >= 0  (i.e. A' beta >= 0 with A picking that entry)\nAmat <- matrix(0, nrow = ncol(X), ncol = 1)\nAmat[disc_idx, 1] <- 1\nbvec <- 0\n\nqp <- solve.QP(Dmat = Dmat, dvec = dvec,\n               Amat = Amat, bvec = bvec, meq = 0)\ndata.frame(coef = names(beta_OLS),\n           OLS  = beta_OLS,\n           CLS  = qp$solution,\n           row.names = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           coef     OLS     CLS\n1   (Intercept) 69869.0 69869.0\n2 rankAssocProf 12831.5 12831.5\n3      rankProf 45287.7 45287.7\n4   disciplineB 14505.2 14505.2\n5 yrs.since.phd   534.6   534.6\n6   yrs.service  -476.7  -476.7\n```\n\n\n:::\n:::\n\n\nOLS already gave a positive `disciplineB` coefficient, so the constraint doesn't bind --- inequality CLS returns the same answer. If the unrestricted estimate had been negative, `solve.QP` would return a solution with that coefficient pinned to exactly $0$ (the boundary) and the other coefficients adjusted accordingly.\n\nA more interesting case: a negative-by-default coefficient with a sign restriction to test what the constrained estimate looks like. We force a `disciplineB` $\\le 0$ constraint, which OLS *does* violate, and watch the projection happen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Reverse the constraint: require disciplineB <= 0 (unrealistic, illustrative)\nAmat[disc_idx, 1] <- -1   # -1 * beta_disciplineB >= 0 means beta_disciplineB <= 0\nbvec <- 0\n\nqp_bind <- solve.QP(Dmat = Dmat, dvec = dvec,\n                    Amat = Amat, bvec = bvec, meq = 0)\ndata.frame(coef = names(beta_OLS),\n           OLS  = beta_OLS,\n           CLS  = qp_bind$solution,\n           row.names = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           coef     OLS        CLS\n1   (Intercept) 69869.0  8.028e+04\n2 rankAssocProf 12831.5  1.381e+04\n3      rankProf 45287.7  4.721e+04\n4   disciplineB 14505.2  2.034e-13\n5 yrs.since.phd   534.6  2.635e+02\n6   yrs.service  -476.7 -3.583e+02\n```\n\n\n:::\n:::\n\n\nNow the constraint binds: the constrained `disciplineB` coefficient is exactly zero, and the other coefficients move to absorb the difference. This is what \"projection onto the feasible region\" looks like in practice.\n\n\n## Partial identification: bounds on the NSW employment ATE\n\nInequality CLS becomes substantive when the *identified set* itself is a polyhedron. The setup: the National Supported Work Demonstration (Lalonde 1986; Dehejia & Wahba 1999) randomly assigned disadvantaged workers to a job-training program. Outcome: positive earnings in 1978.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nu  <- \"https://users.nber.org/~rdehejia/data/nswre74_\"\ncn <- c(\"treat\",\"age\",\"educ\",\"black\",\"hispan\",\"married\",\n        \"nodegree\",\"re74\",\"re75\",\"re78\")\nnsw <- rbind(read.table(paste0(u, \"treated.txt\"), col.names = cn),\n             read.table(paste0(u, \"control.txt\"), col.names = cn))\nnsw$y <- as.numeric(nsw$re78 > 0)\n\ny1 <- mean(nsw$y[nsw$treat == 1])\ny0 <- mean(nsw$y[nsw$treat == 0])\nnaive_ate <- y1 - y0\nc(y1 = y1, y0 = y0, naive_ATE = naive_ate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       y1        y0 naive_ATE \n   0.7568    0.6462    0.1106 \n```\n\n\n:::\n:::\n\n\nThe naive ATE on the experimental sample is about $0.11$ --- an 11 percentage-point employment effect. NSW's actual follow-up was nearly complete. The interesting question is what we could still pin down if a chunk of the sample had been *missing* at follow-up.\n\n### Worst-case bounds\n\nSuppose only $p = 70\\%$ of subjects could be located in 1978. Within each arm, by the law of total probability,\n$$E[Y \\mid X = x] = p \\cdot \\bar{Y}_{\\text{obs}}(x) + (1-p) \\cdot \\underbrace{E[Y \\mid X = x, \\text{missing}]}_{\\text{unknown}}.$$\nThe unknown conditional mean lies in $[0, 1]$ (because $Y$ is binary), giving the *sharp* worst-case bounds:\n$$p\\,\\bar{Y}_{\\text{obs}}(x) \\;\\le\\; E[Y \\mid X{=}x] \\;\\le\\; p\\,\\bar{Y}_{\\text{obs}}(x) + (1-p).$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.7\nlo_y1 <- p * y1;             hi_y1 <- p * y1 + (1 - p)\nlo_y0 <- p * y0;             hi_y0 <- p * y0 + (1 - p)\n\nate_lo <- lo_y1 - hi_y0      # smallest ATE: arm 1 low, arm 0 high\nate_hi <- hi_y1 - lo_y0      # largest:      arm 1 high, arm 0 low\n\nc(ATE_lo = ate_lo, ATE_hi = ate_hi, width = ate_hi - ate_lo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ATE_lo  ATE_hi   width \n-0.2226  0.3774  0.6000 \n```\n\n\n:::\n:::\n\n\nWithout any further assumption, the data + 30% missingness leaves the ATE pinned only to $[-0.22, 0.38]$ --- wide enough that we cannot even sign the effect.\n\n### Tighter bounds via monotone selection\n\nA mild (and often credible) assumption: those *lost* to follow-up are weakly *less* likely to be employed than those we observed in the same arm. Formally, $E[Y \\mid X{=}x, \\text{missing}] \\le \\bar{Y}_{\\text{obs}}(x)$. This tightens the upper bound (the missing group can't contribute more than $\\bar{Y}_{\\text{obs}}$), leaving the lower bound unchanged:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhi_y1_mts <- y1   # MTS: replace 1 with Y_obs\nhi_y0_mts <- y0\n\nate_lo_mts <- lo_y1 - hi_y0_mts\nate_hi_mts <- hi_y1_mts - lo_y0\n\nc(ATE_lo = ate_lo_mts, ATE_hi = ate_hi_mts, width = ate_hi_mts - ate_lo_mts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ATE_lo  ATE_hi   width \n-0.1164  0.3044  0.4209 \n```\n\n\n:::\n:::\n\n\nThe width drops from $0.60$ to $0.42$. The interval still crosses zero --- an 11 pp underlying effect is too small for one mild assumption to settle the sign at 30% missing --- but the bounds *are* informative now.\n\n### The identified set as inequality CLS via `lpSolve`\n\nBoth bounds above came from closed-form arithmetic. With more constraints --- multiple monotonicity assumptions, or a parameter that's not just $\\mu_1 - \\mu_0$ --- the closed-form gets unwieldy. Phrase it instead as a **linear program** over the feasible region.\n\nReparameterize from the regression coefficients to the conditional means $\\bm{\\mu} = (\\mu_0, \\mu_1)$ where $\\mu_x = E[Y \\mid X{=}x]$. The MTS bounds become four inequalities:\n$$\n0.452 \\le \\mu_0 \\le 0.646, \\qquad 0.530 \\le \\mu_1 \\le 0.757.\n$$\nThe ATE is $\\mu_1 - \\mu_0 = \\bm{c}'\\bm{\\mu}$ with $\\bm{c} = (-1, 1)'$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA   <- rbind(c(1,0), c(1,0), c(0,1), c(0,1))\ndir <- c(\">=\", \"<=\", \">=\", \"<=\")\nrhs <- c(lo_y0, hi_y0_mts, lo_y1, hi_y1_mts)\nc_ate <- c(-1, 1)\n\nc(ATE_lo = lp(\"min\", c_ate, A, dir, rhs)$objval,\n  ATE_hi = lp(\"max\", c_ate, A, dir, rhs)$objval)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n ATE_lo  ATE_hi \n-0.1164  0.3044 \n```\n\n\n:::\n:::\n\n\nSame answer (`ATE_lo` ≈ −0.12, `ATE_hi` ≈ 0.30), but now the recipe extends to any number of constraints. Adding another assumption is just another row in `A`, `dir`, `rhs`.\n\n\n## What CLS is for, in one sentence\n\nThe Wald test handles most \"is this restriction true?\" questions without ever computing the restricted estimator. CLS earns its place when you need the *restricted estimator itself*: imposing a theoretical structure as the headline regression (equality form), or estimating an *identified set* when the data alone do not pin $\\bm{\\beta}$ down (inequality form). Both reduce to the same idea: minimize SSE on a restricted set of parameter values.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}